# Generated by Django 5.2.8 on 2026-09-21 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_jobseekerprofile_user_recruiterprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=1024, verbose_name='Street Address')),
                ('address_line_2', models.CharField(blank=True, max_length=1024, verbose_name='Apartment, Suite, Unit, etc.')),
                ('city', models.CharField(max_length=256, verbose_name='City')),
                ('state_province', models.CharField(max_length=256, verbose_name='State/Province/Region')),
                ('postal_code', models.CharField(max_length=20, verbose_name='ZIP/Postal Code')),
                ('country', models.CharField(max_length=2, verbose_name='Country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='given_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='personal_email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='personal_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_profile', to='profiles.useraddress'),
        ),
    ]
