# Generated by Django 5.2.8 on 2026-09-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_useraddress_jobseekerprofile_given_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='given_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='personal_email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
