# Generated by Django 5.2.8 on 2026-09-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_jobseekerprofile_given_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='contact_visibility',
            field=models.CharField(choices=[('PUBLIC', 'Anyone'), ('RECRUITERS', 'Verified recruiters'), ('APPLIED', 'Recruiters I applied to'), ('HIDDEN', 'Only me')], default='APPLIED', max_length=12),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='history_visibility',
            field=models.CharField(choices=[('PUBLIC', 'Anyone'), ('RECRUITERS', 'Verified recruiters'), ('APPLIED', 'Recruiters I applied to'), ('HIDDEN', 'Only me')], default='RECRUITERS', max_length=12),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='identity_visibility',
            field=models.CharField(choices=[('PUBLIC', 'Anyone'), ('RECRUITERS', 'Verified recruiters'), ('APPLIED', 'Recruiters I applied to'), ('HIDDEN', 'Only me')], default='RECRUITERS', max_length=12),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_discoverable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='location_visibility',
            field=models.CharField(choices=[('HIDDEN', 'Only me'), ('CITY', 'City and state'), ('EXACT', 'Full address (only recruiters I applied to)')], default='CITY', max_length=12),
        ),
    ]
