# Generated by Django 5.0 on 2026-09-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobposting_is_active_jobposting_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='required_skills',
            field=models.TextField(blank=True),
        ),
    ]
