# Generated by Django 5.0 on 2026-09-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='base_role',
            field=models.CharField(choices=[('SEEKER', 'Job Seeker'), ('RECRUITER', 'Recruiter'), ('ADMIN', 'Administrator')], default='SEEKER', max_length=20),
        ),
    ]
